### ISSUE TITLE
Přidání jídelny

### ISSUE THREAD

**Issue by vitkolos** [mmrmartin/SmartFoodMenu#1]
Ahoj,
bylo by možné do tvé aplikace přidat jídelnu? Veškeré informace pošlu.
Díky moc.

**Comment by maresmar** [comment]
Ahoj,

určitě ano - existují dva způsoby, jak lze přidat jídelnu - je možné přidat další plugin pro skoro libovolný jídelní systém (vytvořit další plugin) nebo je možné přidat parametry pro existují plugin (aktuálně pro jídelny se systémem iCanteen) U systému iCanteen stačí pouze webová adresa jídelny většinou ;-)

Martin

**Comment by vitkolos** [comment]
Vidím, že to máš všechno v databázi, tak poprosím o přidání jídelny Gymnázia Olgy Havlové, která používá systém iCanteen. Info posílám níže.

Ostrava, Gymnázium Olgy Havlové
http://85.135.20.82:8180/
49.846540, 18.173249
iCanteen 2.14

**Comment by maresmar** [comment]
Jídelna by už měla být dostupná v aplikaci. Do budoucna plánuji na tohle formulář na webu, ale zatím nějak nebyl ještě čas ;-)

Díky za další jídelnu a kdyby něco, tak se klidně zase ozvy...

**Comment by vitkolos** [comment]
Ještě by bylo super, kdyby se jídelny zobrazovaly v abecedním pořadí – je to jen taková maličkost, ale aspoň se člověku bude lépe hledat. :)

**Comment by maresmar** [comment]
Tohle je věc, kterou mám aktuálně v nejbližším plánu (ve výchozím stavu se budou údaje řadit podle abecedy a volitelně podle vzdálenosti)...

Spolu s tím ale musím nejdřív předělat rozhraní na přidávání vlastních jídelen a vůbec to, jak se jídelny teď zobrazují v seznamu (v rámci toho asi udělám právě nějaký ten webový formulář na jídelny)...

Nevím ale, kdy se k tomu úplně dostanu...

**Comment by vitkolos** [comment]
Dobrý, nevadí. :)

**Comment by vitkolos** [comment]
Zjistil jsem, že je tam chybně předvyplněné pole o šifrování – musí tam být nastavená hodnota Vůbec nešifrovat.
Díky za opravu! :)

**Comment by maresmar** [comment]
Opraveno ;-) a díky za zprávu...
