### ISSUE TITLE
Přihlášení bez hesla

### ISSUE THREAD

**Issue by vitkolos** [mmrmartin/SmartFoodMenu#3]
Ahoj, ještě mám jeden dotaz.
Vytvářím webovou aplikaci pro naši školu, která bude pracovat s iCanteen. Nechci ale ukládat heslo uživatelů. Jednou z možností je využít remember-me cookie, nějakým záhadným způsobem se mi ji však nedaří získat a poté přistupovat správně ke stránce. Vím, že tam musí být nějaké konkrétní hlavičky, aby request fungoval. Mohl bys mi to prosím trochu lépe objasnit, jestli o tom něco víš?
Díky moc. :)

**Comment by maresmar** [comment]
Ahoj, 
no já pro to spíš znám pojem session cookie (ještě se alternativně občas používá parametr v adrese)... Obecně v aplikacích tohoto typu musíš ukládat cookies, která získáš od stránky a při otevírání další stránky je zase předávat... Pak záleží na programovacím jazyku, jak se to v něm dělá...

Před hodně lety jsem si na to dělal v PHP knihovnu, ale tedy jsem neuměl tolik programovat ani Anglicky, takže nevím, jaká je její kvalita, ale třeba se Ti bude hodit z hlediska principů...

https://github.com/mmrmartin/fopenHelper/blob/master/fopenhelper.php

Možná bych zmínit, že session cookies mají většinou nějakou "trvanlivost"  (záleží na konfiguraci serveru), takže je dost nepravděpodobné, že Tím můžeš dlouhodobě nahradit přihlašování

https://www.w3schools.com/php/php_sessions.asp

**Comment by vitkolos** [comment]
Díky moc :)
